package com.revature.exceptions.exceptions;

public class UserNotFoundException extends RuntimeException{

}
